### ISSUE TITLE
cannot build mvn clean install

### ISSUE THREAD

**Issue by ttpro1995** [activeviam/autopivot#13]
I use `mvn clean install`

but it bug

`[ERROR] Failed to execute goal on project autopivot: Could not resolve dependencies for project com.activeviam.sandbox:autopivot:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: com.activeviam.activepivot:activepivot-server-spring:jar:5.8.3-jdk8, com.activeviam.activepivot:activepivot-test:jar:5.8.3-jdk8, com.activeviam.activeui:activeui:jar:4.2.11: Could not find artifact com.activeviam.activepivot:activepivot-server-spring:jar:5.8.3-jdk8 in central (https://repo.maven.apache.org/maven2) -> [Help 1]`

**Comment by chamb** [comment]
Hi, the dependencies you're missing are from the ActiveViam aggregation engine. You can download them from the ActiveViam repository, if your organisation is a customer of ActiveViam.

**Comment by ttpro1995** [comment]
> Hi, the dependencies you're missing are from the ActiveViam aggregation engine. You can download them from the ActiveViam repository, if your organisation is a customer of ActiveViam.

No, I am individual who want to use Open-Source software. 
How can I fix this ?

**Comment by chamb** [comment]
Sorry ttpro, AutoPivot requires commercial software from ActiveViam to run, you will not be able to use it if you are not an ActiveViam customer.

**Comment by chamb** [comment]
@ttpro1995 we have just released a new product called Atoti. This free tool developed by ActiveViam allows to create cubes in seconds, using a new python API, and to visualize them interactively. Check it out! https://atoti.io
