### ISSUE TITLE
reading quoted text bug

### ISSUE THREAD

**Issue by dnallicus** [activeviam/autopivot#15]
the line 

FOO,BAR,"FOO,BAR,",TEST

should split as FOO <> BAR <> FOOBAR <> TEST.

Instead, it splits as 
[FOO,BAR,"FOO,BAR,",TEST, null, null]

I think there is an error in the logic around double quotes that appear after a comma.  when you do the following, it will think you are still within quotes if the character before the ending quote was a comma:

				if(c == 0 || sep == text.charAt(c-1)) {
					// Beginning of a new field, delimited by quotes
					withinQuotes = true;
				}
				// or else is it the end of a field?
				else if((c == text.length()-1) || (sep == text.charAt(c+1))) {
					if(!withinQuotes) {
						LOGGER.warning("Unexpected double quote character at the end of a field: " + text);
					}
					withinQuotes = false;
				}

This is incorrect however, as it is actually ending the withinQuotes

**Comment by dnallicus** [comment]
I think adding this to every line that is checking for a start of withinQuotes will fix:
if(c == 0 || (sep == text.charAt(c-1) && !withinQuotes))

**Comment by dnallicus** [comment]
adding this test would be a good idea as well:

		Assertions.assertThat(split("a,\"b,c,\",d", ",")).containsExactly("a", "b,c,", "d");

**Comment by chamb** [comment]
thanks for spotting this. a fix has been merged including your additional unit test.
